version: '3'

services:
  python_dev_experiment:
    user: ${UID}:${GID}
    container_name: 'python_dev_experiment'
    env_file:
      - env_file.env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ../:/opt
    ports:
      - '5000:5000'
    tty: true
    command: mlflow server --backend-store-uri /opt/data/mlflow/mlruns -h 0.0.0.0
